version: '3'
env:
  IMG_PREFIX: 'hkmshb/'

tasks:
  build:
    desc: build docker image
    cmds:
      - docker build -t ${IMG_PREFIX}cgit:latest .

  run:
    desc: run dockerized cgit app
    cmds:
      - |
        docker run --rm \
               --name cgit \
               --publish ${CGIT_PORT}:80 \
               --volume ${PROJECT_DIR}:/srv/projects \
               ${IMG_PREFIX}cgit

