version: '3'
tasks:
  build:
    desc: build docker image
    cmds:
      - docker build -t cgit:latest .

  run:
    desc: run dockerized cgit app
    cmds:
      - |
        docker run --rm \
               --name cgit \
               --publish ${CGIT_PORT}:80 \
               --volume ${PROJECT_DIR}:/srv/projects \
               cgit

